"""Where growth lands, what it is worth, and what happens if you let it run.

Three things live here: a classifier that learns where development goes, a
hedonic surface that prices the result, and a cellular automaton that runs the
two forward year by year under a population path.

One warning governs the whole module and is repeated in the interface, because
it is the easiest thing in applied machine learning to fool yourself with.

**The development labels are synthetic.** They are generated by a stated
process from the cell features, and the classifier is then trained on them. A
high accuracy score therefore measures one thing only: whether the learner can
recover assumptions that were put there on purpose. It is a test of the
pipeline, not evidence about Enschede. Real labels — the municipal register of
consents, or a change-detection layer over successive building footprints —
turn the same code into a real model, and nothing else has to change.

The lineage of the simulation is worth naming too. This is a constrained
cellular automaton in the tradition of SLEUTH and the land-use core of
UrbanSim: a transition rule over neighbouring cells, weighted by accessibility
and filtered by a constraint mask. It is not a novel AI method and calling it
one would be the second-easiest way to fool yourself here.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    brier_score_loss,
    confusion_matrix,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split

# Geometry shared with the access section: a stylised disc of equal area,
# stations at approximate offsets from the central station.
CITY_RADIUS_KM = float(np.sqrt(43 / np.pi))
STATIONS = [(0.0, 0.0), (-2.6, 1.2), (2.8, 0.4)]
BORDER_X_KM = 4.0

# Real Enschede locations that anchor the development picture. Coordinates are
# approximate offsets from the central station in kilometres; programme and
# status are not verified. Replace with the municipal development register.
KNOWN_SITES = pd.DataFrame([
    {"name": "City centre retail core", "kind": "Retail", "x": 0.2, "y": 0.1,
     "label_dx": 0.0, "label_dy": -0.55, "label_align": "left",
     "note": "The Van Heekplein core; the densest retail floorspace in the region."},
    {"name": "Medisch Spectrum Twente", "kind": "Hospital", "x": -0.4, "y": 0.5,
     "label_dx": -0.1, "label_dy": 0.45, "label_align": "right",
     "note": "The regional hospital, rebuilt on a central site — an unusual choice: most "
             "Dutch cities moved acute care to the ring road."},
    {"name": "Kennispark Twente", "kind": "Employment", "x": -2.8, "y": 1.4,
     "label_dx": 0.0, "label_dy": 0.45, "label_align": "left",
     "note": "University campus and science park, adjacent to Kennispark station."},
    {"name": "Roombeek", "kind": "Housing", "x": -0.3, "y": 1.6,
     "label_dx": 0.0, "label_dy": 0.45, "label_align": "left",
     "note": "Rebuilt after the 2000 fireworks depot explosion; a landmark of participatory "
             "Dutch urbanism."},
    {"name": "Zuiderval", "kind": "Mixed use", "x": 0.4, "y": -1.6,
     "label_dx": 0.0, "label_dy": -0.5, "label_align": "left",
     "note": "Mixed-use corridor on the southern approach to the centre."},
    {"name": "De Eschmarke", "kind": "Housing", "x": 2.9, "y": 0.5,
     "label_dx": 0.0, "label_dy": 0.5, "label_align": "right",
     "note": "Eastern housing expansion, built around its own station."},
    {"name": "Usseler Es", "kind": "Industrial", "x": -2.4, "y": -2.2,
     "label_dx": 0.0, "label_dy": -0.5, "label_align": "left",
     "note": "Long-contested industrial land on the south-western edge."},
    {"name": "Technology Base", "kind": "Employment", "x": -1.2, "y": 5.4,
     "label_dx": 0.0, "label_dy": 0.45, "label_align": "left",
     "note": "The former military airbase, north of the built-up area — the site whose radar "
             "and habitat constraints appear in the energy section."},
])


# ---------------------------------------------------------------------
# Cell features
# ---------------------------------------------------------------------

def build_grid(spacing_km: float = 0.2, extent_km: float = 6.5) -> pd.DataFrame:
    """A feature table, one row per cell.

    Features are the ones an urban economist would reach for first — distance
    to the centre, distance to the nearest station, existing density — plus the
    constraint mask that the rest of this platform is about. The mask matters:
    a model without it will happily allocate housing to a raised bog.
    """
    axis = np.arange(-extent_km, extent_km + spacing_km, spacing_km)
    xx, yy = np.meshgrid(axis, axis)
    x, y = xx.ravel(), yy.ravel()

    d_centre = np.hypot(x, y)
    d_station = np.min(
        np.stack([np.hypot(x - sx, y - sy) for sx, sy in STATIONS]), axis=0
    )

    # Existing built density, as the same exponential gradient the access
    # section uses, normalised to [0, 1].
    density = np.exp(-0.35 * d_centre)
    density = density / density.max()

    # Constraint mask. Two things are withheld: the protected habitat on the
    # south-eastern edge standing in for Aamsveen, and everything beyond the
    # national border.
    d_bog = np.hypot(x - 4.2, y + 3.0)
    protected = d_bog < 1.8
    beyond_border = x > BORDER_X_KM
    outside_edge = d_centre > CITY_RADIUS_KM + 1.6

    return pd.DataFrame({
        "x": x, "y": y,
        "d_centre": d_centre,
        "d_station": d_station,
        "density": density,
        "protected": protected,
        "beyond_border": beyond_border,
        "outside_edge": outside_edge,
        "developable": ~(protected | beyond_border),
        "built": d_centre <= CITY_RADIUS_KM,
    })


FEATURES = ["d_centre", "d_station", "density"]


def synthesise_labels(grid: pd.DataFrame, seed: int = 0) -> pd.Series:
    """Generate the development labels the classifier will be trained on.

    Written out explicitly rather than buried, because the whole interpretation
    of the model downstream depends on what is in here. Development is made
    more likely close to the centre, close to a station, and where there is
    already some density to build against; it is made impossible on protected
    land and across the border; and noise is added so the problem is not
    perfectly separable and the metrics mean something.
    """
    rng = np.random.default_rng(seed)
    logit = (
        2.4
        - 0.55 * grid["d_centre"]
        - 0.42 * grid["d_station"]
        + 1.9 * grid["density"]
    )
    probability = 1 / (1 + np.exp(-logit))
    probability = probability.where(grid["developable"], 0.0)
    return (rng.random(len(grid)) < probability).astype(int)


# ---------------------------------------------------------------------
# Classifier registry
# ---------------------------------------------------------------------

CLASSIFIERS = {
    "logistic": ("Logistic regression",
                 lambda **kw: LogisticRegression(max_iter=2000, C=float(kw.get("C", 1.0))),
                 [("C", "Inverse regularisation (C)", 0.01, 10.0, 1.0, 0.01)],
                 "Linear in the log-odds, so every coefficient is readable as an effect. The "
                 "model you should have to argue your way out of before reaching for a forest."),
    "rf": ("Random forest",
           lambda **kw: RandomForestClassifier(
               n_estimators=int(kw.get("n_estimators", 300)),
               max_depth=int(kw.get("max_depth", 8)), random_state=0),
           [("n_estimators", "Trees", 50, 600, 300, 50),
            ("max_depth", "Max depth", 2, 20, 8, 1)],
           "Captures interactions between distance and density without being told they exist. "
           "Pays for it in interpretability."),
    "gbm": ("Gradient boosting",
            lambda **kw: GradientBoostingClassifier(
                n_estimators=int(kw.get("n_estimators", 200)),
                learning_rate=float(kw.get("learning_rate", 0.08)),
                max_depth=int(kw.get("max_depth", 3)), random_state=0),
            [("n_estimators", "Boosting rounds", 50, 500, 200, 50),
             ("learning_rate", "Learning rate", 0.01, 0.5, 0.08, 0.01),
             ("max_depth", "Max depth", 1, 6, 3, 1)],
            "Usually the best score on this problem, which on synthetic labels is exactly the "
            "result you should trust least."),
}


@dataclass
class DevelopmentModel:
    label: str
    model: object
    grid: pd.DataFrame
    metrics: dict
    confusion: np.ndarray
    importance: pd.DataFrame


def fit_development(grid: pd.DataFrame, kind: str = "gbm", params: dict | None = None,
                    seed: int = 0) -> DevelopmentModel:
    """Train, score on a held-out split, and predict development probability."""
    params = params or {}
    label, build, _, _ = CLASSIFIERS[kind]
    y = synthesise_labels(grid, seed)
    X = grid[FEATURES]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=seed, stratify=y)
    model = build(**params)
    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    proba = model.predict_proba(X_test)[:, 1]
    metrics = {
        "Accuracy": float(accuracy_score(y_test, pred)),
        "Precision": float(precision_score(y_test, pred, zero_division=0)),
        "Recall": float(recall_score(y_test, pred, zero_division=0)),
        "ROC AUC": float(roc_auc_score(y_test, proba)),
        # Brier is included because on an allocation problem the calibration of
        # the probability matters more than whether it crosses 0.5.
        "Brier score": float(brier_score_loss(y_test, proba)),
        "Test cells": int(len(y_test)),
        "Base rate": float(y.mean()),
    }

    out = grid.copy()
    out["p_develop"] = model.predict_proba(X)[:, 1]
    out.loc[~out["developable"], "p_develop"] = 0.0
    out["label"] = y

    if hasattr(model, "feature_importances_"):
        importance = pd.DataFrame({
            "feature": FEATURES, "weight": model.feature_importances_})
    else:
        coefs = np.ravel(getattr(model, "coef_", np.zeros(len(FEATURES))))
        importance = pd.DataFrame({"feature": FEATURES, "weight": coefs})

    return DevelopmentModel(label, model, out, metrics,
                            confusion_matrix(y_test, pred), importance)


# ---------------------------------------------------------------------
# Hedonic value surface
# ---------------------------------------------------------------------
#
# Coefficients are elasticities of the kind repeatedly recovered in the
# hedonic literature: value falls with distance from the centre, falls with
# distance from a station, rises with local density up to a point, and carries a
# premium for adjacency to open space. Their signs are well established. Their
# magnitudes here are illustrative, and the resulting surface is synthetic.

VALUE_COEFFICIENTS = {
    "base_eur_m2": 2650.0,
    "centre_decay_per_km": -0.085,
    "station_decay_per_km": -0.035,
    "density_premium": 0.22,
    "green_edge_premium": 0.09,
}


def value_surface(grid: pd.DataFrame, coefficients: dict | None = None) -> pd.Series:
    """Price per square metre implied by accessibility and density."""
    c = {**VALUE_COEFFICIENTS, **(coefficients or {})}
    green_adjacency = np.clip((grid["d_centre"] - CITY_RADIUS_KM + 1.2) / 1.2, 0, 1)
    log_value = (
        np.log(c["base_eur_m2"])
        + c["centre_decay_per_km"] * grid["d_centre"]
        + c["station_decay_per_km"] * grid["d_station"]
        + c["density_premium"] * grid["density"]
        + c["green_edge_premium"] * green_adjacency
    )
    return np.exp(log_value)


def value_uplift(grid: pd.DataFrame, added_density: pd.Series,
                 coefficients: dict | None = None) -> pd.Series:
    """Change in price per m² when density rises by `added_density`.

    Only the density term moves, which is the point: accessibility is fixed by
    geography until someone builds a station, so the uplift a development
    captures is bounded by the density premium alone.
    """
    c = {**VALUE_COEFFICIENTS, **(coefficients or {})}
    before = value_surface(grid, c)
    after_grid = grid.copy()
    after_grid["density"] = np.clip(grid["density"] + added_density, 0, 1.6)
    return value_surface(after_grid, c) - before


# ---------------------------------------------------------------------
# Simulation
# ---------------------------------------------------------------------

@dataclass
class SimulationResult:
    yearly: pd.DataFrame
    final_grid: pd.DataFrame
    frames: dict[int, pd.DataFrame]


def simulate(
    grid: pd.DataFrame,
    population_path: pd.DataFrame,
    densification_share: float = 0.6,
    respect_constraints: bool = True,
    station_weighting: float = 1.0,
    persons_per_hectare_new: float = 65.0,
    spacing_km: float = 0.2,
) -> SimulationResult:
    """Run the growth path over the grid, year by year.

    Each year's population increment is split between densifying cells that are
    already built and converting cells that are not. Conversion is allocated in
    order of development probability, optionally reweighted toward the stations
    and optionally ignoring the constraint mask — the last of which exists so
    the cost of the constraints can be read directly off the difference between
    two runs.
    """
    cell_ha = (spacing_km * 1000) ** 2 / 10_000
    state = grid.copy()
    state["converted"] = False
    state["added_people"] = 0.0

    weight = state["p_develop"].to_numpy(dtype=float).copy()
    if station_weighting != 1.0:
        weight = weight * np.exp(-station_weighting * 0.25 * state["d_station"].to_numpy())
    if respect_constraints:
        weight = np.where(state["developable"].to_numpy(), weight, 0.0)

    order = np.argsort(-weight)
    order = order[weight[order] > 0]
    next_cell = 0

    path = population_path.sort_values("year").reset_index(drop=True)
    rows, frames = [], {}
    built_mask = state["built"].to_numpy().copy()

    for i in range(1, len(path)):
        year = int(path.loc[i, "year"])
        increment = float(path.loc[i, "population"] - path.loc[i - 1, "population"])

        densified = increment * densification_share if increment > 0 else increment
        greenfield = increment - densified

        converted_this_year = 0
        if greenfield > 0:
            needed = int(np.ceil(greenfield / (persons_per_hectare_new * cell_ha)))
            take = order[next_cell:next_cell + needed]
            state.loc[state.index[take], "converted"] = True
            built_mask[take] = True
            next_cell += len(take)
            converted_this_year = len(take)

        # Densification lands on already-built cells in proportion to their
        # development probability: the same accessibility that attracts
        # greenfield conversion attracts infill.
        if densified != 0:
            w = np.where(built_mask, state["p_develop"].to_numpy(), 0.0)
            total = w.sum()
            if total > 0:
                state["added_people"] += densified * w / total

        built_area = built_mask.sum() * cell_ha / 100  # km²
        rows.append({
            "year": year,
            "population": float(path.loc[i, "population"]),
            "built_up_km2": built_area,
            "built_up_density": float(path.loc[i, "population"]) / max(built_area, 1e-6),
            "cells_converted": converted_this_year,
            "cumulative_converted": int(state["converted"].sum()),
        })

        if year % 5 == 0 or i == len(path) - 1:
            snapshot = state.copy()
            snapshot["built_now"] = built_mask
            frames[year] = snapshot

    yearly = pd.DataFrame(rows)

    added_density = state["added_people"] / (persons_per_hectare_new * cell_ha)
    state["added_density"] = np.clip(added_density, 0, 1.5)
    state["value_before"] = value_surface(grid)
    state["value_uplift"] = value_uplift(grid, state["added_density"])
    state["built_now"] = built_mask

    return SimulationResult(yearly, state, frames)


def scenario_delta(a: SimulationResult, b: SimulationResult) -> pd.DataFrame:
    """Difference between two runs, which is how a scenario is actually read."""
    merged = a.yearly.merge(b.yearly, on="year", suffixes=("_a", "_b"))
    merged["built_up_km2_delta"] = merged["built_up_km2_b"] - merged["built_up_km2_a"]
    merged["density_delta"] = merged["built_up_density_b"] - merged["built_up_density_a"]
    return merged
